apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
  namespace: default
  labels:
    app: ratelimit
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  template:
    metadata:
      labels:
        app: ratelimit
        version: v1
    spec:
      containers:
        - name: ratelimit
          image: europe-west1-docker.pkg.dev/wavemm-sre-takehome-joan/containers/ratelimit
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 6070
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: REDIS_URL
              value: "localhost:6379"
          volumeMounts:
            - name: ratelimit-config
              mountPath: /etc/ratelimit/config
        - name: statsd-exporter
          image: docker.io/prom/statsd-exporter:v0.21.0
          imagePullPolicy: Always
          args: ["--statsd.mapping-config=/etc/statsd-exporter/config.yaml"]
          ports:
            - containerPort: 9125
            - containerPort: 9102
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: statsd-exporter-config
              mountPath: /etc/statsd-exporter
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
      volumes:
        - name: ratelimit-config
          configMap:
            name: ratelimit-config
        - name: statsd-exporter-config
          configMap:
            name: statsd-exporter-config