apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: default
  labels:
    app: ratelimit
    version: v1
spec:
  ports:
    - name: http-ratelimit
      port: 8080
      targetPort: 8080
    - name: http-debug
      port: 6070
      targetPort: 6070
    - name: grpc-ratelimit
      port: 8081
      targetPort: 8081
  selector:
    app: ratelimit